version: "3.9"

services:
  pini-bot:
    image: alejoide/pini-bot:latest
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - database

networks:
  database:
    name: mongo
    external: true
